- job:
    description: null
    disabled: false
    name: !!python/unicode '3. Full Cloud - Deploy'
    parameters:
    - string:
        default: bundle.yaml
        description: Name of bundle to deploy. This option is overridden by BUNDLE_URL
          or BUNDLE_FILE
        name: BUNDLE_NAME
        trim: false
    - string:
        default: ''
        description: 'Specify a URL for the bundle to be deployed. Overrides BUNDLE_NAME '
        name: BUNDLE_URL
        trim: false
    - file:
        description: Upload a bundle file to deploy. Overrides BUNDLE_URL and BUNDLE_NAME
        name: ./bundle.yaml
    - text:
        default: ''
        description: |-
          Custom config options applied after bundle deployment but before waiting, one per line

          application,key=value
          e.g.
          ceph-osd,osd-devices=/srv/ceph-osd
        name: OVERRIDE_BUNDLE_CONFIG
        trim: false
    - string:
        default: test
        description: ''
        name: SLAVE_NODE_NAME
        trim: false
    - string:
        default: ''
        description: ''
        name: WORKSPACE
        trim: false
    - string:
        default: slave
        description: ''
        name: SLAVE_LABEL
        trim: false
    - text:
        default: ''
        description: Paste a full bundle to deploy. Will override all other bundle
          settings.
        name: BUNDLE_PASTE
        trim: false
    - string:
        default: ''
        description: |-
          Set data-port for neutron-gateway charm before waiting for deployment to complete.
          e.g.
          br-ex:eth1
          If this value is not set, we will wait for the machines to be deployed, and then use the MAAS API to get the second configured interface on the machine. We will also confirm this interface appears in dmesg for the neutron-gateway unit.
        name: NEUTRON_DATAPORT
        trim: false
    - string:
        default: mosci
        description: ''
        name: MAAS_OWNER
        trim: false
    - string:
        default: vNSmAQUASAkVcpFu2N:khmguH2CFh7phsjBBF:vZCKGMea5U9sfrzzWvGwBGv9KDySz3HJ
        description: ''
        name: RUXTON_API_KEY
        trim: false
    - string:
        default: ''
        description: ''
        name: ICARUS_API_KEY
        trim: false
    - choice:
        choices:
        - ruxton
        - icarus
        - s390x
        description: ''
        name: CLOUD_NAME
    - bool:
        default: false
        description: Enable this option if you're deploying on top of a "full cloud
          openstack deployment"
        name: OVERCLOUD_DEPLOY
    - string:
        default: ''
        description: For overcloud deployment
        name: CONTROLLER_NAME
        trim: false
    - string:
        default: ''
        description: for overcloud deployment
        name: MODEL_NAME
        trim: false
    - choice:
        choices:
        - amd64
        - arm64
        - ppc64el
        - s390x
        description: ''
        name: ARCH
    - bool:
        default: true
        description: True if this is an openstack deployment
        name: OPENSTACK
    pipeline-scm:
      lightweight-checkout: true
      scm:
      - git:
          branches:
          - '*/admcleod_test'
          url: https://github.com/openstack-charmers/bot-control.git
      script-path: ./config/pipelines-mosci/3_full_cloud_deploy/Jenkinsfile.groovy
    project-type: pipeline
    properties:
    - raw:
        xml: |
          <com.sonyericsson.rebuild.RebuildSettings plugin="rebuild@1.28">
          <autoRebuild>false</autoRebuild>
          <rebuildDisabled>false</rebuildDisabled>
          </com.sonyericsson.rebuild.RebuildSettings>
    - raw:
        xml: |
          <hudson.plugins.throttleconcurrents.ThrottleJobProperty plugin="throttle-concurrents@2.0.1">
          <maxConcurrentPerNode>0</maxConcurrentPerNode>
          <maxConcurrentTotal>0</maxConcurrentTotal>
          <categories class="java.util.concurrent.CopyOnWriteArrayList" />
          <throttleEnabled>false</throttleEnabled>
          <throttleOption>project</throttleOption>
          <limitOneJobWithMatchingParams>false</limitOneJobWithMatchingParams>
          <paramsToUseForLimit />
          </hudson.plugins.throttleconcurrents.ThrottleJobProperty>
    triggers: []
